# 开发环境配置
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: dev

patchesStrategicMerge:
- patch.yaml

replicas:
- name: myapp
  count: 1

images:
- name: myapp
  newTag: latest